HYPER_PARAMS:
  MAX_EPOCHS: !!int 10
  LEARNING_RATE: !!float 1e-3
  BATCH_SIZE: !!int 96
  SWA_LRS: !!float 1e-2
  LR_SCHEDULER_PATIENCE: !!int 5
  LR_SCHEDULER_FACTOR_: !!float 0.5

  EARLY_STOPPING:
    PATIENCE: !!int 50

DATA_PARAMS:
  TEST_SIZE: !!float 0.25
  RANDOM_STATE: !!int 42
  NORMALIZE: False
  SHUFFLE_TRAIN: False
  SHUFFLE_VALID: False
  NUM_WORKERS: !!int 0
  NUMPY_DATA: False
  IS_ROOT: True
  TPC_SETTINGS:
    TPC_CLUSTERS: !!int 5
    SPLIT_FRACTION:
      - !!float 0.4
      - !!float 0.2
      - !!float 0.4
    EDGE_ITER: !!int 0 # spacing at edges - ++i will double the spacing for each iteration
    MIDDLE_ITER: !!int 0 # spacing in the middle
    PLOT_SPACING: False # Turn this flag on if you want to plot cluster spacing


PYTORCH_LIGHTNING_PARAMS:
  NUM_NODES: !!int 1
  PRECISION: !!int 16
  LIMIT_TRAIN_BATCHES: !!float 0.5
  ACCELERATOR: 'cpu'
  DEVICES: 1

PATHS:
  DATA_PATH_TRAIN: 'train.root'
  DATA_PATH_VALID: 'valid.root'
  SAVE_PATH: '~/models/pytorch'
  MODEL_DIR: 'my_network'

MODEL:
  NAME: 'FNet'
  OUTPUT_SHAPE: !!int 5
  FILTER: !!int 32

temp:
  - temp1: 1
  - temp2: 2
